namespace LcfSharp.Rpg.Events
{
    public enum MoveCommandCode
    {
        MoveUp = 0,
        MoveRight = 1,
        MoveDown = 2,
        MoveLeft = 3,
        MoveUpright = 4,
        MoveDownright = 5,
        MoveDownleft = 6,
        MoveUpleft = 7,
        MoveRandom = 8,
        MoveTowardsHero = 9,
        MoveAwayFromHero = 10,
        MoveForward = 11,
        FaceUp = 12,
        FaceRight = 13,
        FaceDown = 14,
        FaceLeft = 15,
        Turn90DegreeRight = 16,
        Turn90DegreeLeft = 17,
        Turn180Degree = 18,
        Turn90DegreeRandom = 19,
        FaceRandomDirection = 20,
        FaceHero = 21,
        FaceAwayFromHero = 22,
        Wait = 23,
        BeginJump = 24,
        EndJump = 25,
        LockFacing = 26,
        UnlockFacing = 27,
        IncreaseMovementSpeed = 28,
        DecreaseMovementSpeed = 29,
        IncreaseMovementFrequence = 30,
        DecreaseMovementFrequence = 31,
        SwitchOn = 32,
        SwitchOff = 33,
        ChangeGraphic = 34,
        PlaySoundEffect = 35,
        WalkEverywhereOn = 36,
        WalkEverywhereOff = 37,
        StopAnimation = 38,
        StartAnimation = 39,
        IncreaseTransp = 40,
        DecreaseTransp = 41
    }
}
